[Wiki example of SVD](https://en.wikipedia.org/wiki/Singular_value_decomposition#Example)

The following ⁠4×5⁠ matrix ⁠$\displaystyle \mathbf {M}$⁠ can be decomposed as $\displaystyle \mathbf {U\Sigma V} ^{*}$:

In [22]:
import numpy as np

M = np.array([
    [4, 8, 8, 0, 0],
    [-3, -6, -6, 0, 0],
    [-4, 4, -2, 0, 0],
    [0, 0, 0, -4, 3]
])

U_EIG = np.linalg.eig(M @ M.T)
U = U_EIG.eigenvectors

SIGMA = U_EIG.eigenvalues
idx = np.argsort(SIGMA)[::-1]
U = U[:, idx]
SIGMA = SIGMA[idx]

SIGMA = np.sqrt(SIGMA)
SIGMA = np.diag(SIGMA)
SIGMA = np.pad(SIGMA, ((0, 0), (0, 1)))

V_EIG = np.linalg.eig(M.T @ M)
V = V_EIG.eigenvectors
idx = np.argsort(V_EIG.eigenvalues)[::-1]
V = -1 * V
V = V[:, idx].T

print('M = \n', M)
print()
print('U = \n', U)
print()
print('SIGMA = \n', SIGMA)
print()
print('V = \n', V)
print()
print('U * SIGMA * V = \n', U @ SIGMA @ V)

M = 
 [[ 4  8  8  0  0]
 [-3 -6 -6  0  0]
 [-4  4 -2  0  0]
 [ 0  0  0 -4  3]]

U = 
 [[ 0.8  0.   0.   0.6]
 [-0.6  0.   0.   0.8]
 [ 0.   1.   0.   0. ]
 [ 0.   0.   1.   0. ]]

SIGMA = 
 [[15.  0.  0.  0.  0.]
 [ 0.  6.  0.  0.  0.]
 [ 0.  0.  5.  0.  0.]
 [ 0.  0.  0.  0.  0.]]

V = 
 [[ 0.33333333  0.66666667  0.66666667 -0.         -0.        ]
 [-0.66666667  0.66666667 -0.33333333 -0.         -0.        ]
 [-0.         -0.         -0.         -0.8         0.6       ]
 [ 0.66666667  0.33333333 -0.66666667 -0.         -0.        ]
 [-0.         -0.         -0.         -0.6        -0.8       ]]

U * SIGMA * V = 
 [[ 4.  8.  8.  0.  0.]
 [-3. -6. -6.  0.  0.]
 [-4.  4. -2.  0.  0.]
 [ 0.  0.  0. -4.  3.]]
